services:
  movietheater:
    build:
      context: . #Chỉ định thư mục hiện tại (ký hiệu bằng dấu chấm .) làm ngữ cảnh xây dựng (build context). Nếu đặt ở ngữ cảnh khác thì phải sửa lại path. Ngữ cảnh xây dựng là thư mục mà Docker sẽ sử dụng để tìm tệp Dockerfile và các tệp cần thiết khác để xây dựng hình ảnh Docker
      dockerfile: MovieTheater/Dockerfile #Chỉ định tên file Dockerfile trong quá trình build container.
    ports:
      - "8080:8080" #có thể là 8080 thay vì 80 nếu docker file chỉ định là mở cổng 8080
      - "8081:8081" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./wwwroot/qrcodes:/app/wwwroot/qrcodes # Ánh xạ thư mục QR code
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123@123abc  #có thể viết cách khác đưa password trực tiếp ở đây SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network
networks:
  app-network:

volumes:
  sql_data: